# Generated by Django 2.1.5 on 2019-02-01 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=8)),
                ('fechaLanzamiento', models.CharField(max_length=20)),
                ('peso_gigas', models.CharField(max_length=5)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('url_descargar', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=8)),
                ('fechaLanzamiento', models.CharField(max_length=20)),
                ('peso_gigas', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='aplicacion',
            name='sistemaOperativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.SistemaOperativo'),
        ),
    ]
