# Generated by Django 2.1.5 on 2019-02-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='codigo_barras',
            field=models.CharField(default=786106704083, max_length=13),
            preserve_default=False,
        ),
    ]
